server:
  port: 8002

#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:8761/eureka/


spring:
  application:
    name: system-core
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.service.host:127.0.0.1}:${mysql.service.port:3306}/jcc_auth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: ${mysql.service.username:jtao}
    password: ${musql.service.password:jtao.123}
    #druid相关配置
    druid:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: '*'



mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.bin.cloud.system.core.base.entity.po
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      column-like: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL


#测试级别是DEBUG
#日志 级别 DEBUG -->INFO -->WARN -->ERROR
logging:
  level:
    com.bin.cloud.system.core.base.dao.*: debug