server:
  port: 8080

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: system-web